= Introduction
:page-topic-type: guide
:page-toclevels: 2
:description: The Couchbase SQLAlchemy Connector provides data visualization and exploration for the Couchbase platform, using Apache Superset.

[abstract]
--
{description}

The Couchbase SQLAlchemy Connector integrates Couchbase Analytics tabular views and Capella Columnar instances with the open-source data exploration and visulaization platform Apache  Superset.
--


== Prerequisites

First catch your hare.

== Install the CouchbaseSQL Alchemy Connector
To install the Couchbase SQLAlchemy Connector, open the command prompt (`cmd`), and enter the following:
+
[source, console]
----
pip install couchbase-sqlalchemy
----

== Install Apache Superset
Download and install Apache Superset following the official documentation.

== Configure the Connection in Superset:

Launch Apache Superset and set up a new database connection. 
Select Couchbase as the database type and provide the necessary connection details.

There are four types of connection possible:

[tabs]
====
Capella Columnar::
+
--
Connecting Apache Superset with Capella Columnar, you'll require the following details:
+
. Connection String: Obtain this from your running Capella Columnar environment. This string typically includes necessary connection details such as the host address and port.
images::get-connection-string.png[get connection string]
+
. Get UserName and Password from Access Control.
images::get-username-pswrd-from-accesscontrol.png[get username and password from access control]
+
. Set up the server
images::setup-the-server.png[setup the server] 
+

--

Couchbase Analytics::
+
--


--

Capella Analytics::
+
--


--

====


== Create Tabular Analytics views
In Couchbase Analytics, define tabular analytics views. These views act as non-materialized views, specifying schemas along with primary and foreign keys for collections or subqueries.
https://docs.couchbase.com/columnar/sqlpp/5a_views.html#TAV

...

